config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :astros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astro.rb
class Astro < ApplicationRecord
	belongs_to :tipo
end

app/models/tipo.rb
class Tipo < ApplicationRecord
	has_many :astros
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/astros_controller.rb
class AstrosController < ApplicationController
  before_action :set_astro, only: [:show, :edit, :update, :destroy]

  # GET /astros
  # GET /astros.json
  def index
    @astros = Astro.all
    @tipo = Tipo.all
  end

  # GET /astros/1
  # GET /astros/1.json
  def show
     @tipo = Tipo.all
  end

  # GET /astros/new
  def new
    @astro = Astro.new
    @tipo = Tipo.all
  end

  # GET /astros/1/edit
  def edit
    @tipo = Tipo.all
  end

  # POST /astros
  # POST /astros.json
  def create
    @astro = Astro.new(astro_params)
    @tipo = Tipo.all
    respond_to do |format|
      if @astro.save
        format.html { redirect_to @astro, notice: 'Astro was successfully created.' }
        format.json { render :show, status: :created, location: @astro }
      else
        format.html { render :new }
        format.json { render json: @astro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /astros/1
  # PATCH/PUT /astros/1.json
  def update
    respond_to do |format|
      if @astro.update(astro_params)
        format.html { redirect_to @astro, notice: 'Astro was successfully updated.' }
        format.json { render :show, status: :ok, location: @astro }
      else
        format.html { render :edit }
        format.json { render json: @astro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /astros/1
  # DELETE /astros/1.json
  def destroy
    @astro.destroy
    respond_to do |format|
      format.html { redirect_to astros_url, notice: 'Astro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_astro
      @astro = Astro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def astro_params
      params.require(:astro).permit(:nombre, :tipo_id, :distancia, :descripcion, :fecha)
    end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astros_helper.rb
module AstrosHelper
end

app/helpers/tipos_helper.rb
module TiposHelper

end

app/views/astros/_form.html.erb
<%= form_for(astro) do |f| %>
  <% if astro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(astro.errors.count, "error") %> prohibited this astro from being saved:</h2>

      <ul>
      <% astro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

 <!-- <div class="field">

  </div>
--> 
 <div class="dropdown">
    <%= f.label :tipo_id %>
    <%= f.number_field :tipo_id %>
<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Tipo
  </button>

   <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <% @tipo.each do |t| %>
    <button class="dropdown-item"><%= t.tipo %> - <%= t.id %> </button>
    <% end %>
  </div>
 </div>


<br>

  <div class="field">
    <%= f.label :distancia %>
    <%= f.text_field :distancia %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/astros/edit.html.erb
<h1>Editing Astro</h1>

<%= render 'form', astro: @astro %>

<%= link_to 'Ver', @astro %> |
<%= link_to 'Atras', astros_path %>

app/views/astros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Astros</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Distancia</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @astros.each do |astro| %>
        <% @tipo.each do |t| %>

        <% if t.id == astro.tipo_id %>
        <tr>
        <td><%= astro.nombre %></td>
        <td><%= t.tipo %></td>
        <td><%= astro.distancia %></td>
        <td><%= astro.descripcion %></td>
        <td><%= astro.fecha %></td>
        <td><%= link_to 'Ver', astro %></td>
        <td><%= link_to 'Editar', edit_astro_path(astro) %></td>
        <td><%= link_to 'Eliminar', astro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
        <% end %>
    <% end %>
        <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Agregar nuevo astro', new_astro_path %>

app/views/astros/new.html.erb
<h1>New Astro</h1>

<%= render 'form', astro: @astro %>

<%= link_to 'Atras', astros_path %>

app/views/astros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @astro.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <% @tipo.each do |t| %>
    <% if @astro.tipo_id == t.id %>
          <%= t.tipo %>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Distancia:</strong>
  <%= @astro.distancia %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @astro.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @astro.fecha %>
</p>

<%= link_to 'Editar', edit_astro_path(@astro) %> |
<%= link_to 'Atras', astros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Astronomia</title>
    <%= csrf_meta_tags %>
       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  	

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <ul class="nav justify-content-center sticky-top" id="colores">
  <li class="nav-item">
    <a class="nav-link" href="/astros" id="texto">Ver Astros</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="/astros/new" id="texto">Agregar Astros</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/tipos/new" id="texto">Agregar Tipo</a>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="/tipos" id="texto">Ver Tipo</a>
  </li>
</ul>
  <hr>



   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
   
  <div class="container">

  	<%= yield %>	
  </div>
  </body>



  <hr>
<footer style="padding-bottom: 0;">
    <div class="container">
        <div class="row middle-xs between-xs">
            <div class="col-xs-12 col-sm-4 col-md-4 col-sm-offset-2">
                <div class="logo">Josue Lopez.</div>
            </div>              
           
        </div>
    </div>
</footer>
</html>

app/views/tipos/_form.html.erb
<%= form_for(tipo) do |f| %>
  <% if tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Ver', @tipo %> |
<%= link_to 'Atras', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.tipo %></td>
        <td><%= link_to 'Ver', tipo %></td>
        <td><%= link_to 'Editar', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Eliminar', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar nuevo tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @tipo.tipo %>
</p>

<%= link_to 'Editar', edit_tipo_path(@tipo) %> |
<%= link_to 'Atras', tipos_path %>